### PR TITLE
Polyhierarchy improvements

### PR DESCRIPTION
**Pull request by seweissman**
Hi Katie. I added some code to dndTree.js that takes into account polyhierarchy when adding/removing/moving nodes in the tree by replicating changes to nodes with the same name. So, for example, if you move Novae->Supernovae to Stars->Supernovae, then VariableStars->Cataclysmic->Novae will also be updated. This makes the tree less confusing when there is a lot of polyhierarchy. It also fixes some issues with the diffs not reflecting all the changes when nodes occurring in multiple branches are only updated in one place.

I also removed the restriction on adding multiple new nodes with the same name.

### CODE REVIEW

**Comment by katieefrey** [comment]
I tried these changes out and it seems to be working for the most part.  This will definitely help alleviate some of the confusion when working with the highly polyhierarchiced terms!

I decided to copy the changes into my code by hand, rather than just overwrite my file, because I have two slightly different versions of dndTree.js running on the sorting tool now (one for the top level categories dropdown page, and one for the individual chunks...mostly because they load the json at different times).  I may have made a mistake in copying the code, so I'll mention the two things I noticed, and you can let me know if its happening on your end too?

1) When I tried to add a test term, as soon as I clicked the "Add Node" button the sorting tool froze.  I could still move the new node to a new location, and I can still move other nodes...but I cannot move the entire structure around on the screen as I could before.  Once I move a term, however, the structure is unfrozen and can be shifted around again.

2) When I move a term to orphans that appears under different parent terms, it did not make the change in all locations.  For example "Peculiar giants" is found under "Peculiar stars" AND "Gas giants".  When I moved P-giants from P-stars to orphans, P-giants underneath Gas giants remained.  I'm sure this is not a trivial fix, and I'm not sure it's worth attempting to fix, but just thought I should mention it.

**Comment by seweissman** [comment]
I will see if I can reproduce 1 on my machine.

2 is by design. Since there is no way to delete a term from a branch without moving it to orphans, I didn't want to assume that moving a node to orphans meant that we wanted to delete it everywhere. We could probably account for this when printing the diff, but maybe that would be overkill. Really the whole reason for implementing this change was so that we'd fix the case where we had parent->child and moved child to orphans, but the diff would only include "+ophans NT child" and NOT "-parent NT child" because parent->child still existed elsewhere in the tree. If we can duplicate the removal of the child across the entire tree, then the diff will contain "-parent NT child" and then we can ignore whatever goes into the orphans bucket.

Does this make sense? I worry perhaps I'm thinking of the tree sorter in a different way than was originally intended.

**Comment by katieefrey** [comment]
Regarding item 2, that makes sense.  We sometimes want to remove a child term from one area of the hierarchy, but not necessarily delete it all together.

As for item 1, I am looking at this again today, and I'm still having the problem where adding a new node kind of freezes the whole screen until I move a term.  It seems to be conflicting with something in d3.v3.min.js?  I get this error when I use Firefox's developer web console:

Unexpected value translate(NaN,NaN)scale(1) parsing transform attribute. d3.v3.min.js:1:0

**Comment by katieefrey** [comment]
Ok, I'm remembering more detail about this whole thing and this is a clear account of what is happening:

The dndTree.js file you edited works perfectly as described if I download a copy of this repository and run it independently.  The "visual editor" folder in this gtihub repo is a stand alone module that just runs.

The live website where the general sorting tool and chunk sorting tools are a different animal.  For one they actually use two slightly different versions of the dndTree.js file, so I can't just replace my dndTree.js files with yours.  For another, they are integrated into the python/flask environment I built to make the chunk sorting tools easier to manage.  There is some sort of problem occurring that I just cant pinpoint.  I could send you the two different dndTree.js files I'm using on the live site, but without the rest of the context in which to test them, would that be helpful?

**Comment by seweissman** [comment]
Sorry. I've been super busy and I haven't had as much time to look at this
as I'd like. If you send me the versions actually used on the site and I
can see if I can note what might be causing the problem. If I can't figure
it out, maybe we can do a debug session together at AAS, assuming we think
that it's still worth improving the sorter.

**Comment by katieefrey** [comment]
I needed to move all of the scripts to a different repo so that they didn't get in the way of anyone looking to download just the UAT.  I hope the files I emailed you are able to help you figure out the weird problems I was having.  I would like to get those updates into the live versions!

**Pull request closed without merging**
